### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by traincrisis** [CammiesCorner/Cammies-Minecart-Tweaks#49] opened 2023-08-23 15:15 UTC
If you make a train with this rolling stock:
F C C C H H H R R R F
Where F stands for furnace minecart, C for chest minecart, H for hopper minecart and R for an regular empty minecart after launching this train minecraft will crash. Video for that: https://www.youtube.com/watch?v=7p4-DjhftRc
In crash log it says:

https://pastebin.com/4DYfGXhN

End of crash log

Edit: I saw that if you make an train longer than 6 carts it will crash (For example the train has 5 carts and 1 locomotive at front making 6 carts)

**Comment by traincrisis** [comment] 2024-12-02 13:12
when fix

**Comment by CammiePone** [comment] 2024-12-03 20:28
duplicate of

**Closed as completed by CammiePone** 2024-12-03 20:28 UTC
